### ISSUE TITLE
Relative percent cover calculation

### ISSUE THREAD

**Issue by zoey-rw** [admahood/neonPlantEcology#1]
Thanks for creating this package! I was wondering about the difference between % cover and _relative_ % cover in the outputs of `get_longform_cover()` - how are plant observations weighted for each?  I'm also a bit confused about the use of the "trace" argument.

For context, I have a list that links plant genus to category. Using this list, I am interested in which outputs would be most representative of the per-plot dominance of specific groups.

Thanks again,
Zoey

**Comment by admahood** [comment]
Hey @zoey-rw, glad you like the package! 

Cover vs Relative Cover:
So cover is the absolute cover as measured in the field (and averaged to the scale of your choosing) and relative cover is relative to the cover of the other plants. So, a plot with 40% cover of species A and 10% cover of species B would have those values for cover, then it would be 80% and 20% for relative cover.

Trace Cover:
Trace cover is an arbritrary cover value assigned to the presence-only detections that are made. I think Bartlett 2019 is cited in the readme for more details, but basically, the field technicians measure percent cover in 1m2 subplots that are nested within 10m and 100m square subplots. For the 10m subplots, any species that did not occur in the 1m subplot is recorded as present, and then anything that's no in the 10 or 1 m subplots is recorded as present in the 100m subplots. So, in order to give a cover value, neondiveRsity assigns a 0.5% cover by default to those presence-only detections. It might be better to do 0.1 though. 

I think for your use, you could use relative cover of the groups as a measure of dominance, or you could stick with cover, and then you can calculate dominance another way. 

Cheers,
Adam

**Comment by zoey-rw** [comment]
Thanks very much for this explanation, definitely clears up my confusion!
